version: "3.7"

services:
  jellyfin:
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/anton/jellyfin/config:/config
      - /home/anton/bucket/media:/data
    restart: unless-stopped
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY
      - WIREGUARD_ADDRESSES
      - SERVER_COUNTRIES
      - OWNED_ONLY
    restart: unless-stopped
