version: "3.7"

services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/hotio/jellyfin
    ports:
      - "8096:8096"
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/Vancouver
    volumes:
      - /home/anton/jellyfin/config:/config
      - /home/anton/bucket/media:/data
